backend_repo_workdir: '/home/ubuntu/yaptide'
backend_repo_version: master

backend_password: "password"

backend_cluster: ""
backend_cert_auth_url: ""
backend_backend_external_url: "89.168.73.251:5000"
backend_keycloak_base_url: 'https://sso.pre.plgrid.pl'
backend_keycloak_realm: 'PLGrid'

backend_ssl_crt: "server.crt"
backend_ssl_key: "server.key"

backend_postgres_db: "yaptide"
backend_postgres_user: "yaptide"
backend_postgres_password: "yaptide"

ansible_become: false
