---
# Based on: https://github.com/oracle/oci-ansible-collection/tree/master/samples/compute/always_free_launch_compute_instance
- name: Launch or teardown a compute instance
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    # common networking definitions
    quad_zero_route: "0.0.0.0/0"
    TCP_protocol: "6"
    SSH_port: "22"

    vcn_name: "yaptide"
    vcn_cidr_block: "10.0.0.0/16"
    vcn_dns_label: "yaptide"

    ig_name: "yaptide"

    ssh_keypair_path: "~/.ssh/yaptide"

    route_table_name: "yaptide"
    # route all internet access to our Internet Gateway
    route_table_rules:
        - cidr_block: "{{ quad_zero_route }}"
          network_entity_id: "{{ ig_id }}"

    subnet_cidr: "10.0.0.48/28"
    subnet_name: "yaptide"
    subnet_dns_label: "yaptide"

    securitylist_name: "yaptide"

    instance_shape: "VM.Standard3.Flex"
    instance_shape_ocpus: 1
    instance_shape_mem_gbs: 24
    instance_hostname: "yaptide"

    #########################################
    # Tenancy specific configuration
    # *Note* - Override the following variables based on your tenancy
    # or set a valid value for the corresponding environment variable
    #########################################

    # TODO in final PR:
    # instance_ad: "{{ lookup('env', 'OCI_AVAILABILITY_DOMAIN') }}"
    instance_ad: "kHMI:EU-FRANKFURT-1-AD-3" # can also select AD-1 or AD-2

    # TODO in final PR:
    # instance_compartment: "{{ lookup('env', 'OCI_COMPARTMENT_ID') }}"
    instance_compartment: "ocid1.tenancy.oc1..aaaaaaaaxsclzs4afggrkoumjx2rbvsvx2vdaywovhiwwy6t4y453dcehbcq"

    # TODO in final PR:
    # instance_image: "{{ lookup('env', 'OCI_IMAGE_ID') }}"
    instance_image: "ocid1.image.oc1.eu-frankfurt-1.aaaaaaaatk6awqpvv5wvorrfbq5ofesx2bmj22n6gpbkxfvccyaryz2xr34q"
    # This image is Canonical-Ubuntu-22.04-2023.10.13-0

  tasks:
    - import_tasks: setup.yml
      when: mode == "deploy"
    - import_tasks: deploy.yml
      when: mode == "deploy"
    - import_tasks: clean.yml
      when: mode == "clean"
