frontend_repo_workdir: '/home/ubuntu/ui'
frontend_repo_version: master

ansible_become: false

frontend_backend_hostname: "localhost"
frontend_backend_url: "89.168.73.251:5000"
frontend_ui_hostname: "localhost"
frontend_ui_url: "89.168.73.251:80"

frontend_keycloak_base_url: 'https://sso.pre.plgrid.pl'
frontend_keycloak_realm: 'PLGrid'
frontend_keycloak_client_id: 'yaptide-staging'

frontend_ssl_crt: "server.crt"
frontend_ssl_key: "server.key"
